// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef hex2bin_h
#define hex2bin_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "MyTable.h"
#include <FL/Fl_Output.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *main_window;
  MyHexBinTable *table;
  Fl_Output *base_addr_oput;
  Fl_Output *len_oput;
  Fl_Input_Choice *inp_ch;
  Fl_Button *save_btn;
  Fl_Input *input_file_edt;
  Fl_Button *find_file_btn;
  Fl_Button *open_file_btn;
};
#endif
